module ChessBoard where

import           Data.Map (Map)
import qualified Data.Map as Map

initBoardGame =
  Map.fromList
    [ ("a1", "<div id='a1' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("b1", "<div id='b1' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("c1", "<div id='c1' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("d1", "<div id='d1' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("e1", "<div id='e1' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("f1", "<div id='f1' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("g1", "<div id='g1' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("h1", "<div id='h1' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("a2", "<div id='a2' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("b2", "<div id='b2' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("c2", "<div id='c2' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("d2", "<div id='d2' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("e2", "<div id='e2' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("f2", "<div id='f2' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("g2", "<div id='g2' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("h2", "<div id='h2' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("a3", "<div id='a3' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("b3", "<div id='b3' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("c3", "<div id='c3' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("d3", "<div id='d3' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("e3", "<div id='e3' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("f3", "<div id='f3' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("g3", "<div id='g3' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("h3", "<div id='h3' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("a4", "<div id='a4' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("b4", "<div id='b4' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("c4", "<div id='c4' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("d4", "<div id='d4' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("e4", "<div id='e4' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("f4", "<div id='f4' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("g4", "<div id='g4' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("h4", "<div id='h4' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("a5", "<div id='a5' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("b5", "<div id='b5' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("c5", "<div id='c5' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("d5", "<div id='d5' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("e5", "<div id='e5' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("f5", "<div id='f5' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("g5", "<div id='g5' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("h5", "<div id='h5' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("a6", "<div id='a6' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("b6", "<div id='b6' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("c6", "<div id='c6' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("d6", "<div id='d6' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("e6", "<div id='e6' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("f6", "<div id='f6' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("g6", "<div id='g6' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("h6", "<div id='h6' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("a7", "<div id='a7' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("b7", "<div id='b7' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("c7", "<div id='c7' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("d7", "<div id='d7' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("e7", "<div id='e7' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("f7", "<div id='f7' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("g7", "<div id='g7' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("h7", "<div id='h7' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("a8", "<div id='a8' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("b8", "<div id='b8' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("c8", "<div id='c8' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("d8", "<div id='d8' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("e8", "<div id='e8' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("f8", "<div id='f8' onClick='move(this.id)'  class='white'>#movement</div>")
    , ("g8", "<div id='g8' onClick='move(this.id)'  class='black'>#movement</div>")
    , ("h8", "<div id='h8' onClick='move(this.id)'  class='white'>#movement</div>")
    ] :: Map String String

initPlayerPieces1 =
  Map.fromList
    [ ("a1", "&#9820;")
    , ("b1", "&#9822;")
    , ("c1", "&#9821;")
    , ("d1", "&#9819;")
    , ("e1", "&#9818;")
    , ("f1", "&#9821;")
    , ("g1", "&#9822;")
    , ("h1", "&#9820;")
    , ("a2", "&#9821;")
    , ("b2", "&#9821;")
    , ("c2", "&#9821;")
    , ("d2", "&#9821;")
    , ("e2", "&#9821;")
    , ("f2", "&#9821;")
    , ("g2", "&#9821;")
    , ("h2", "&#9821;")
    ] :: Map String String

initPlayerPieces2 =
  Map.fromList
    [ ("a7", "&#9817;")
    , ("b7", "&#9817;")
    , ("c7", "&#9817;")
    , ("d7", "&#9817;")
    , ("e7", "&#9817;")
    , ("f7", "&#9817;")
    , ("g7", "&#9817;")
    , ("h7", "&#9817;")
    , ("a8", "&#9814;")
    , ("b8", "&#9816;")
    , ("c8", "&#9815;")
    , ("d8", "&#9813;")
    , ("e8", "&#9812;")
    , ("f8", "&#9815;")
    , ("g8", "&#9816;")
    , ("h8", "&#9814;")
    ] :: Map String String
