module ChessBoard where

import           Data.Map (Map)
import qualified Data.Map as Map

initBoardGame =
  Map.fromList
    [ ("a1", "<div class='white'>#movement</div>")
    , ("b1", "<div class='black'>#movement</div>")
    , ("c1", "<div class='white'>#movement</div>")
    , ("d1", "<div class='black'>#movement</div>")
    , ("e1", "<div class='white'>#movement</div>")
    , ("f1", "<div class='black'>#movement</div>")
    , ("g1", "<div class='white'>#movement</div>")
    , ("h1", "<div class='black'>#movement</div>")
    , ("a2", "<div class='black'>#movement</div>")
    , ("b2", "<div class='white'>#movement</div>")
    , ("c2", "<div class='black'>#movement</div>")
    , ("d2", "<div class='white'>#movement</div>")
    , ("e2", "<div class='black'>#movement</div>")
    , ("f2", "<div class='white'>#movement</div>")
    , ("g2", "<div class='black'>#movement</div>")
    , ("h2", "<div class='white'>#movement</div>")
    , ("a3", "<div class='white'>#movement</div>")
    , ("b3", "<div class='black'>#movement</div>")
    , ("c3", "<div class='white'>#movement</div>")
    , ("d3", "<div class='black'>#movement</div>")
    , ("e3", "<div class='white'>#movement</div>")
    , ("f3", "<div class='black'>#movement</div>")
    , ("g3", "<div class='white'>#movement</div>")
    , ("h3", "<div class='black'>#movement</div>")
    , ("a4", "<div class='black'>#movement</div>")
    , ("b4", "<div class='white'>#movement</div>")
    , ("c4", "<div class='black'>#movement</div>")
    , ("d4", "<div class='white'>#movement</div>")
    , ("e4", "<div class='black'>#movement</div>")
    , ("f4", "<div class='white'>#movement</div>")
    , ("g4", "<div class='black'>#movement</div>")
    , ("h4", "<div class='white'>#movement</div>")
    , ("a5", "<div class='white'>#movement</div>")
    , ("b5", "<div class='black'>#movement</div>")
    , ("c5", "<div class='white'>#movement</div>")
    , ("d5", "<div class='black'>#movement</div>")
    , ("e5", "<div class='white'>#movement</div>")
    , ("f5", "<div class='black'>#movement</div>")
    , ("g5", "<div class='white'>#movement</div>")
    , ("h5", "<div class='black'>#movement</div>")
    , ("a6", "<div class='black'>#movement</div>")
    , ("b6", "<div class='white'>#movement</div>")
    , ("c6", "<div class='black'>#movement</div>")
    , ("d6", "<div class='white'>#movement</div>")
    , ("e6", "<div class='black'>#movement</div>")
    , ("f6", "<div class='white'>#movement</div>")
    , ("g6", "<div class='black'>#movement</div>")
    , ("h6", "<div class='white'>#movement</div>")
    , ("a7", "<div class='white'>#movement</div>")
    , ("b7", "<div class='black'>#movement</div>")
    , ("c7", "<div class='white'>#movement</div>")
    , ("d7", "<div class='black'>#movement</div>")
    , ("e7", "<div class='white'>#movement</div>")
    , ("f7", "<div class='black'>#movement</div>")
    , ("g7", "<div class='white'>#movement</div>")
    , ("h7", "<div class='black'>#movement</div>")
    , ("a8", "<div class='black'>#movement</div>")
    , ("b8", "<div class='white'>#movement</div>")
    , ("c8", "<div class='black'>#movement</div>")
    , ("d8", "<div class='white'>#movement</div>")
    , ("e8", "<div class='black'>#movement</div>")
    , ("f8", "<div class='white'>#movement</div>")
    , ("g8", "<div class='black'>#movement</div>")
    , ("h8", "<div class='white'>#movement</div>")
    ] :: Map String String

initPlayerPieces1 =
  Map.fromList
    [ ("a1", "&#9820;")
    , ("b1", "&#9822;")
    , ("c1", "&#9821;")
    , ("d1", "&#9819;")
    , ("e1", "&#9818;")
    , ("f1", "&#9821;")
    , ("g1", "&#9822;")
    , ("h1", "&#9820;")
    , ("a2", "&#9821;")
    , ("b2", "&#9821;")
    , ("c2", "&#9821;")
    , ("d2", "&#9821;")
    , ("e2", "&#9821;")
    , ("f2", "&#9821;")
    , ("g2", "&#9821;")
    , ("h2", "&#9821;")
    ] :: Map String String

initPlayerPieces2 =
  Map.fromList
    [ ("a7", "&#9817;")
    , ("b7", "&#9817;")
    , ("c7", "&#9817;")
    , ("d7", "&#9817;")
    , ("e7", "&#9817;")
    , ("f7", "&#9817;")
    , ("g7", "&#9817;")
    , ("h7", "&#9817;")
    , ("a8", "&#9814;")
    , ("b8", "&#9816;")
    , ("c8", "&#9815;")
    , ("d8", "&#9813;")
    , ("e8", "&#9812;")
    , ("f8", "&#9815;")
    , ("g8", "&#9816;")
    , ("h8", "&#9814;")
    ] :: Map String String
